version: "3"
services:
  db:
    image: "postgres:14"
    container_name: "nextcartdb"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
        PGDATA: pgdata
    ports:
      - "5432:5432"
    volumes:
      - ".postgres/.db:/var/lib/postgresql/data"
    restart: unless-stopped
