@cartId = 87dee802-c862-4069-936c-f41130460010
@productId = 00000000-c862-4069-936c-f41130460003
@dockerhost = http://localhost:5000
@localhost = http://localhost:5095
@kubeHost = http://192.168.49.2:30903
@host = {{localhost}}


### Create cart
POST {{host}}/cart/
Content-Type: application/json

{
    "cartId": "{{cartId}}"
}

### Get sample cart
GET {{host}}/cart/{{cartId}}

### Add item to cart
POST {{host}}/cart/{{cartId}}/items
Content-Type: application/json

{
    "productId": "{{productId}}"
} 

### Increase quantity
POST {{host}}/cart/{{cartId}}/items/{{productId}}/increasequantity

### Decrease quantity
POST {{host}}/cart/{{cartId}}/items/{{productId}}/decreasequantity

### Remove item from cart
DELETE {{host}}/cart/{{cartId}}/items/{{productId}}

### Clear cart
POST {{host}}/cart/{{cartId}}/clear
