@cartId = 87dee802-c862-4069-936c-f41130460005
@productId = 00000000-c862-4069-936c-f41130460003

### Create cart
POST http://localhost:5095/cart/
Content-Type: application/json

{
    "cartId": "{{cartId}}"
}

### Get sample cart
GET http://localhost:5095/cart/{{cartId}}

### Add item to cart
POST http://localhost:5095/cart/{{cartId}}/items
Content-Type: application/json

{
    "productId": "{{productId}}"
} 

### Increase quantity
POST http://localhost:5095/cart/{{cartId}}/items/{{productId}}/increasequantity

### Decrease quantity
POST http://localhost:5095/cart/{{cartId}}/items/{{productId}}/decreasequantity

### Remove item from cart
DELETE http://localhost:5095/cart/{{cartId}}/items/{{productId}}

### Clear cart
POST http://localhost:5095/cart/{{cartId}}/clear
