apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcart
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcart
subjects:
  - kind: ServiceAccount
    name: nextcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcart
  labels:
    app: nextcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcart
  template:
    metadata:
      annotations:
      labels:
        app: nextcart
    spec:
      serviceAccountName: nextcart
      securityContext:
        runAsUser: 101
      containers:
        - name: member
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.member.image.repository }}:{{ .Values.member.image.tag }}"
          imagePullPolicy: { { .Values.member.image.pullPolicy } }
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nextcart
spec:
  type: { { .Values.member.service.type } }
  ports:
    - port: { { .Values.member.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nextcart
