apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcart
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcart
subjects:
  - kind: ServiceAccount
    name: nextcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcart
  labels:
    app: nextcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcart
  template:
    metadata:
      labels:
        app: nextcart
    spec:
      serviceAccountName: nextcart
      securityContext:
        runAsUser: 101
      containers:
        - name: member
          securityContext:
            allowPrivilegeEscalation: false
          image: nextcart-api:1.0.0
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NEXTCART_USE_KUBERNETES
              value: "true"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcart-service
  labels:
    app: nextcart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcart-service
  template:
    metadata:
      labels:
        app: nextcart-service
    spec:
      serviceAccountName: nextcart
      securityContext:
        runAsUser: 101
      containers:
        - name: member
          securityContext:
            allowPrivilegeEscalation: false
          image: nextcart-service:1.0.0
          imagePullPolicy: Never
          env:
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NEXTCART_USE_KUBERNETES
              value: "true"
            - name: MARTEN_CONNECTIONSTRING
              value: "Host=host.minikube.internal;Port=5432;Database=postgres;Username=user;Password=password"
            - name: MARTEN_SCHEMANAME
              value: "public"

---
apiVersion: v1
kind: Service
metadata:
  name: nextcart
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nextcart
